config/routes.rb
Rails.application.routes.draw do

 namespace :admin do
    # Add dashboard for your models here
    resources :projects
   

    root to: "projects#index" # <--- Root route
  end

	root 'pages#index'
		get  '/works',   to: 'projects#index'
	  	get  '/info',   to: 'pages#info'
  		get  '/contact', to: 'pages#contact'
  		get '/projects/:title', to: "projects#show"
  		resources :projects
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]
	validates :title, presence: true, length: { minimum: 3 }
  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	
  	

	def next
	    Project.where("id < ?", id).order("id DESC").first || Project.last
	end

	def previous
	    
	    Project.where("id > ?", id).order("id ASC").first || Project.first
	end

	

	def should_generate_new_friendly_id? #will change the slug if the name changed
    	title_changed?
  end

	 def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Project.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Project.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 respond_to :html, :js
	  def index
		@project = Project.find(params[:id])
		project.next = Project.where("id > ?", id).order("id ASC").first || Project.first
   		project.previous = Project.where("id < ?", id).order("id DESC").first || Project.last
  		
  		
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
respond_to :html, :js


	 def index
    
  		
	  	@projects = Project.all.order(created_at: :desc)
		@project = Project.first
			 respond_to do |format|
		      format.html
		      format.js
	  		end
	  end
	
	  def info
	    
		respond_to do |format|
	      format.html
	      format.js
			end
		end

		def contact
				respond_to do |format|
		      format.html # index.html.erb
		      format.js
			end
		end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  # GET /projects
  # GET /projects.json
  def index
    
  @projects = Project.all
  respond_to do |format|
      format.html { render 'projects/index' }
      format.js
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
   @project = Project.friendly.find(params[:title])
  # @credits = JSON.parse(@project.credits)
  respond_to do |format|
      format.html { render 'projects/show' }
      format.js
  end
  end


  # GET /projects/new

def edit
    @project = Project.find params[:id]
  end

  # POST /products
  # POST /products.json
  def create
    @project = Project.new(product_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @project.category_id = params[:category_id]
    respond_to do |format|
      if @project.update(product_params)
        format.html { redirect_to @project, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # POST /projects
  # POST /projects.json


  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json

  # DELETE /projects/1
  # DELETE /projects/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
     
     @project = Project.friendly.find(params[:title])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "DEADBUTCOOL"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end


  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/remote_link_pagination_helper.rb
require 'will_paginate/view_helpers/link_renderer'
require 'will_paginate/view_helpers/action_view'
module RemoteLinkPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    def link(text, target, attributes = {})
      attributes['data-remote'] = true
      super
    end
  end
end

app/views/fields/paperclip_field/_form.html.erb
<%= f.label field.attribute %>
<%= f.file_field field.attribute %>

app/views/fields/paperclip_field/_index.html.erb
# app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/paperclip_field/_show.html.erb
# app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>DEAD BUT COOL</title>
    
   <%= render 'partials/meta' %>

  </head>

  <body>
  <%= render "partials/header" %>
  <div id="maincontent">
    <%= yield %>
  
    <%= render "partials/footer" %>
    </div>
  </body>


</html>

app/views/pages/contact.html.erb
<% provide(:title, "CONTACT") %>
<div class="static-contact">
<div class="content">
	<div class="mailandtel">
  <h1 style="margin:0;">
  	General inquiries:
	<a href="mailto:info@deadbutcool.com" style=" color:inherit;
    "><h1 style="margin:0;">info@deadbutcool.com</h1></a>
	<br>
	Business inquiries:
	<a href="mailto:hello@deadbutcool.com" style=" color:inherit;
	    "><h1 style="margin:0;">hello@deadbutcool.com</h1></a>
	<br>
	
	<a href="tel:+7-322-674-88-03" style=" color:inherit;
	    "><h1 style="margin:0;">Tel.: +7 322 674 88 03</h1></a>
	</h1></div>

	<div class="info">
		<p id="column1">We always looking forward to communicate.  Don’t hesitate to write us directly
		<p></p><br>
		<p >Or keep in touch via <span class="facebook">Facebook</span>, <span class="soundcloud">  Soundcloud</span> or <span class="youtube">Youtube</span>
	</div>
</div>

</div>

app/views/pages/index.html.erb

<div class="static" style="width:83%;">
      <h1>Independent studio crafting sound-design for Fendi, Chanel, Saint-Lauren  and <a href="/works" style="word-wrap: break-word;color:white; font-family: Favorit_Regular;font-style: normal;font-stretch: normal;font-weight:100;line-height: normal;letter-spacing: normal;font-size: inherit;text-decoration:underline;">more</a>
      </h1>
  
</div>



<div id="slider-wrapper" style="position:relative;">
  
<div id="curtain" style="
    z-index: 7;
    position: absolute;
top:0;
  
  position:absolute;
    "></div>
 <div class="slider" style="position:relative;">

     <!-- ruby loop start -->

    <% @projects.each do |project| %>
<li> 
  <div class="top" style="position:relative;">

    <div class="wrapper" style="position:relative;">
        

        <!-- Vimeo iframe -->
        <iframe class='video' src='https://player.vimeo.com/video/<%= project.link %>?api=1&title=0&byline=0&portrait=0&transparent=0&color=ffffff&autoplay=0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>

  </div>
  



  
   <p> 
    <span style="opacity:0.5;left: 50px;"><%= project.previous.title.upcase  %></span>
  </p>
<div style="position:relative;left:20px;">
   <div class="centered" style="position:absolute;">
    <p> 
      <span> 
        <!-- <%= image_tag("icon-nosound.svg", style: "line-height:1em;", id: 'set-volume')%>-->&nbsp;<%= project.title.upcase  %> </span>
    </p> 
  </div> 
</div>
  <span style="opacity:0.5;">
   <%= project.next.title.upcase %> 
  </span>
 </div>

        <%= link_to "VIEW PROJECT CASE", project_path(project), class: 'viewcase', style: "display:none;" %>
</li>
 
    <% end %>
  <!-- ruby loop end -->


    </div>




<div class="bottom-left"><img class="slider-controls" src="assets/icon-previous-mobile@3x-0675c69133cc60426a9eb87ebb38a14b2c345b8dbbfd2aaae4ef91b0f0db0694.png" alt="Icon previous mobile@3x" width="100" height="50" /></div>
<div class="bottom-center">
  <img id="playpause" src="assets/icon-pause-desktop@3x.png", width="60" height="60"/>
</div>
  <div class="bottom-right"><img class="slider-controls" src="assets/icon-next-mobile@3x-156721a4bfcd29e022cc6f1d6aa922e475119022e33ac0babd4722bcc7d37b71.png" alt="Icon next mobile@3x" width="100" height="50" /></div>
    
    <div class="top-left">
      <p>LEFT
    </div>

<div class="top-center">

   <p id="top-center" style="    display: inline-block;line-height:1;">
      <img id="setvolume" src="assets/icon-nosound@3x.png"/> 
   </p> 
 
</div>

    <div class="top-right">
      <p>RIGHT
    </div>

 <p class="centered-title">





</div>


app/views/pages/index.js.erb
$("#footer").hide();
$("#maincontent").hide();
$(".nav").show();
$(window).scrollTop(0);
$("#maincontent").fadeIn(2000);
$("#maincontent").html( "<%= escape_javascript( render( :partial => "index" ) ) %>" );
$("#footer").fadeIn(3000);
 $(document).ready(function(){
  $('.slider').bxSlider({

      onSlideAfter: function (currentSlideNumber, totalSlideQty, currentSlideHtmlObject) {
       //
      },  
    onSliderLoad: function () {
  //
    
    },
    
    
  });
});

$(function() {
        /* Vimeo Player */
        var togSrc = ["assets/icon-pause-desktop@3x.png", "assets/icon-play-desktop@3x.png"],
        togSrcSound = ["assets/DBC_SOUNDOFF.svg", "assets/DBC_SOUNDON.svg"],
            video,
            volume_level = 0;
            video_state = 'paused',
            $pauseplay = $("#playpause"),
            $setvolume = $("#setvolume"),
            $viewcase = $('.viewcase'),
            initVideo = function() {
                video_state = 'playing';
                $pauseplay[0].src = togSrc[0];
                $setvolume[0].src = togSrcSound[0];
               
                if (!video.data('init')) {
                    video.data('init', true);
                    video.on("finish", function(){
                            video.vimeo("unload");
                            // video_state = 'paused';

                            console.log("Finished " + video_state);
                            $('.bottom-right').click();
                        })
                        .vimeo("play")
                        //.vimeo("setVolume", 0);
                }

                video.vimeo("play");
            };
        
        if ($('.video').length) {
            $('.slider').bxSlider({

                onSliderLoad: function(slideElement){
                    
                   
                    caseLink = $viewcase.attr("href");
                    $("#viewcase").attr("href", caseLink);
                   
                },
                onSlideBefore: function (slideElement, oldIndex, newIndex) {
                    console.log('slide before', slideElement, oldIndex, newIndex);
                    
                    video.vimeo("pause");
                    video_state = 'paused';

                    video = slideElement.find('.video');
                   // projecttitle =   slideElement.find('.centered');
                    initVideo();
                    //$('.top-center').prepend($setvolume);
                },
                onSlideAfter: function (slideElement, oldIndex, newIndex) {
                    console.log('slide after', slideElement, oldIndex, newIndex);
                    xxvideo = slideElement.find('.viewcase');
                    xxxy = xxvideo.attr("href");
                   $("#viewcase").attr("href", xxxy);

                }
            });

            video = $('.slider').find('.video:first');
            initVideo();
            //$("#sound-control-center").prepend$('.centered');
            $('.video-wrapper').append($pauseplay);

            // Play / Pause toggle
            $pauseplay.on('click', function(){
                console.log(video_state);
                
                if (video_state == 'paused') {
                    this.src =  togSrc[0];
                    video.vimeo("play");
                    video_state = 'playing';
                } else {
                    this.src =  togSrc[1];
                    video.vimeo("pause");
                    video_state = 'paused';
                }
            });
              

             $setvolume.on('click', function(){

              if (volume_level == 1) {
                this.src =  togSrcSound[0];
                video.vimeo("setVolume", 0);
                volume_level = 0;
                console.log( "Volume is", volume_level ); 
              } else {
                this.src =  togSrcSound[1]; 
                video.vimeo("setVolume", 1);
                console.log( "Volume is", volume_level ); 
                volume_level = 1; 
              }
             //
           });     
        }
    });

app/views/pages/info.html.erb
<% provide(:title, "INFO") %>

<div class="static-info">
	<div class="independent">
   <h1>Independent studio crafting sound-design for Fendi, Chanel, Saint-Lauren  and <a href="/works"><h1 style="margin:0;text-decoration:underline;display:inline-block;">more</h1></a></h1></div>

		<div class="info"><p>I was always somebody who felt quite sorry for myself, what I had not got compared to my friends, how much of a struggle my life seemed to be compared to others. I was caught up in a web of 	   negativity and needed someone or something to help me to escape.
			<br><br>
			During an afternoon at work one day, aged around twenty one, a colleague I was working with started to talk to me. What he said was quite upsetting and disturbing, however would have a profound effect on my future. He said to me:
			<br><br>
			“Your quite a depressive person, aren’t you?”
			<br><br>
			“Am I?”
			<br><br>
			I said in a shocked voice as I believed I was no different to anybody else. He continued:
			<br><br>
			“Yes you are. You very rarely smile, you are negative about most issues and you always seem to be carrying the world on your shoulders”.
			<br><br>
			This man was aged around fifty three and continued:
			<br><br>
			“I used to be like you and then I was given some advice, of which I am now going to relay to you. When you feel down, depressed or sorry for yourself, read the newspapers or watch the news on the television. You may then realise that you are in fact one of the lucky ones.”
			<br><br>
			I listened and thought about what he had said. I had never been a big reader or watcher of the news, but decided to start. The advice was totally correct, the news from around the world and even my own country was quite shocking. I realised that the worries I had were actually quite trivial and that I needed to cherish everyday and start to look on the bright side of life.</p>
	</div>
</div>

  
  
  
  

app/views/pages/works.html.erb
<style>

* {
   box-sizing: border-box;
}

.container {
  width:100%;
  max-width: 2000px;
  overflow:hidden;
  
}

img {
  max-width:500px;
  
}

.item {
  width:25%;
  float:left;
 }



@media screen and (max-width:1000px) {
  
/*   body {
    background-color:#ddf;
  } */
  
  .item {
    width:33.3%;
  }

}


@media screen and (max-width:700px) {
  
/*   body {
    background-color:#cdd;
  } */
  
  .item {
    width:50%;
  }
  
}

@media screen and (max-width:515px) {
  
/*   body {
    background-color:#ded;
  } */
  
  .item {
    width:100%;
    height: 300px;
  }

}



</style>



<div class="container">
  
  <div class="item">
    <img src="http://78.media.tumblr.com/e94bf2b37de5025087807868016e373c/tumblr_ou37kv2iib1uduh1yo1_500.gif">
   
  </div>
  
  <div class="item">
    <img src="http://placehold.it/400x300">
    
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
    
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
    
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
   
  </div>
  
  <div class="item">
    <img src="http://78.media.tumblr.com/33b093d2a11186257cb02d65e9a86951/tumblr_o5ydb4MlTA1rcr5dwo1_1280.jpg">
   
  </div>
  
  <div class="item">
    <img src="http://placehold.it/400x300">
   
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
    
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
    
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
    
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
  
  </div>
  
  <div class="item">
    <img src="http://placehold.it/1600x900">
    
  </div>
  
</div> <!--close container-->

app/views/partials/_footer.html.erb
<div class="push"></div>
<div id="footer">
	<p><%= current_year = Time.new.year %>. Dead But Cool</p>
</div>

app/views/partials/_header.html.erb
<ul id="header">
  <li style="display: inline-block;" class="logo-right"><a href="/" style="font-family:Canela-Light;font-weight:100;text-decoration:none;">DEAD BUT COOL</a></li>

  <div id="deskmenu">
    <li><a id="viewcase" style="text-decoration: none;display:none;" href="#" >VIEW PROJECT CASE</a></li>
    <li><a id="closebtn" style="    position: fixed;
    right: 0;text-decoration: none;display:none;" onclick="return false;"> CLOSE</a></li>
    <li><%= link_to "WORKS", works_path, class: 'nav' %></li>
    <li><%= link_to "INFO", info_path, class: 'nav' %></li>
    <li><%= link_to "CONTACT", contact_path, class: 'nav' %></li>
    </div>
 <li>
   <li id="menu" class="openbtn">MENU</li>
   

   
</ul>
   <div id="myNav" class="overlay">
  
  
  <div class="overlay-content">
     <%= link_to "WORKS", works_path %>
     <%= link_to "INFO", info_path, id: "info" %>
     <%= link_to "CONTACT", contact_path, id: "contact" %>
    
  </div>

  <div class="social" style="white-space: nowrap;display: inline-block;">
   <p> <span class="youtube">YOUTUBE</span>&nbsp;<span class="facebook">FACEBOOK</span>&nbsp;<span class="soundcloud">SOUNDCLOUD</span></p>

  </div>
</div>

<script>
//OVERLAY MENU/CLOSE


$("#menu").click(function() { 
$('#myNav').toggle(1, function() {
    if($(this).is(':visible')) { 
        $("html").addClass("modal-open");
        $("#menu").text("CLOSE");
        
    }
    else {
        
        $("#menu").text("MENU");
        $("html").removeClass("modal-open");
    }
}); 
});
// underline current nav menu
$("#header li a").click(function() {

  $("#header li").removeClass("active");                                     
  $(this).parent().addClass("active");
});
</script>

app/views/partials/_meta.html.erb
	<%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
     <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
	 
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
  




    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
 

app/views/projects/index.html.erb
<div class="grid">
  <% @projects.each do |project| %>

    <div class="img-item" style="position: relative;">

      	<%= link_to (image_tag(project.image, class: 'img-responsive', style: "height:100%;")), project, class: 'gallery' %> 

<%=   link_to(project) do %> 
        
            
             <p class="brand"><%= project.brand.upcase %></p>

       
  <% end %> 
	</div>
   
 
  <% end %> 

</div>

app/views/projects/show.html.erb
<div class="project-top">
  <div class="wrapper">
    <iframe src="https://player.vimeo.com/video/<%= @project.link %>?title=0&byline=0&portrait=0&transparent=0&autoplay=1&color=ffffff" width="640" height="480" frameborder="0"  webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" data-ready="true"></iframe>
  </div>
</div>

  <div class="static-info" style="margin-bottom:50px;"> 

  <h1 style="width:66%;"><%= @project.title %></h1>
  <div class="info">
   <%= simple_format(@project.description, {}, wrapper_tag: "p") %>
     </div><br>
<div class="img_wrap">
      <%= image_tag @project.image, class: 'project_img' %>
</div>


<div class="credits">
  <h1>Credits:<br> 
<a style="text-decoration: none;" href="<%=@project.link1 %>" target="_blank"> <h1 style="margin:0;" ><%= @project.credit1 %></h1></a>
<a style="text-decoration: none;" href="<%=@project.link2 %>" target="_blank"> <h1 style="margin:0;" ><%= @project.credit2 %></h1></a>
<a style="text-decoration: none;" href="<%=@project.link3 %>" target="_blank"> <h1 style="margin:0;" ><%= @project.credit3 %></h1></a>  
<a style="text-decoration: none;" href="<%=@project.link4 %>" target="_blank"> <h1 style="margin:0;" ><%= @project.credit4 %></h1></a>
    </h1>
</div>

<!-- PREVIOUS/NEXT on >=TABLET  view end-->
<div class="prev-next-container">

   
             <%= link_to(project_url(@project.previous)) do %>
              <p style='float:left;'>PREVIOUS PROJECT 
            <% end %>

              
                
              <%= link_to(project_url(@project.next)) do %>
              <p style='float:right;'>NEXT PROJECT
            <% end %>

</div>
<br>
<br>
<br>

<div class="left" style="float:left;"><%=   link_to (image_tag("icon-previous-mobile@3x.png", id: 'control-img', class: 'control', :style => "float:left;line-height:1em;", size: "100x50")), project_url(@project.previous) %>
</div>
 <%= link_to(project_url(@project.previous)) do %>
<div class="brandlink" style="float:left;">
  <p>&nbsp;<%= @project.previous.brand.upcase %></p>
</div>
<% end %>


<div class="right" style="float:right;"> <%= link_to (image_tag("icon-next-mobile@3x.png", id: 'control-img', class: 'control', :style => "float:right;line-height:1em;", size: "100x50")), project_url(@project.next) %>
</div>


  <%= link_to(project_url(@project.next)) do %>
<div class="brandlink" style="float:right;">
  <p> <%= @project.next.brand.upcase %>&nbsp;&nbsp;
</div>
<% end %>